name: "Setup PHP devpack Action"
description: "Setup PHP and PHP devpack for Windows"

inputs:
  phpversion:
    description: "PHP release version to download"
    required: true
  tspart:
    description: "Thread-safety (nts or ts)"
    required: true
  vs:
    description: "The Visual Studio version"
    required: true
  arch:
    description: "The architecture to build for (x64 or x86)"
    required: true
  baseurl:
    description: "The php.net release download base URL"
    required: true
  workspace:
    description: "The destination workspace (project GITHUB_WORKSPACE)"
    required: true

runs:
  using: "composite"
  steps:

    - name: "Setup cache"
      id: "cache"
      uses: actions/cache@v3
      with:
        path: |
          ./php-bin
          ./php-dev
        key: php-${{inputs.phpversion}}-${{inputs.tspart}}-${{inputs.vs}}-${{inputs.arch}}

    - if: steps.cache.outputs.cache-hit != 'true'
      name: "download PHP"
      id: "php"
      shell: bash
      run: |
        PHP_ZIP="php-${{inputs.phpversion}}-${{inputs.tspart}}-${{inputs.vs}}-${{inputs.arch}}.zip"
        curl -LO ${{inputs.baseurl}}/${PHP_ZIP}
        7z x ${PHP_ZIP} -o./php-bin
        ls
        ls ./php-bin

    - if: steps.cache.outputs.cache-hit != 'true'
      name: "download development pack"
      id: "devpack"
      shell: bash
      run: |
        DP_ZIP="php-devel-pack-${{inputs.phpversion}}-${{inputs.tspart}}-${{inputs.vs}}-${{inputs.arch}}.zip"
        DP_DIR="php-${{inputs.phpversion}}-devel-${{inputs.vs}}-${{inputs.arch}}"
        curl -LO ${{inputs.baseurl}}/${DP_ZIP}
        7z x ${DP_ZIP} -o.
        mv ./${DP_DIR} ./php-dev
        ls ./php-dev

#    - name: "Move files to workspace"
#      id: "paths"
#      shell: powershell
#      run: |
#        Move-Item -Path .\php-bin -Destination ${{inputs.workspace}}
#        Move-Item -Path .\php-dev -Destination ${{inputs.workspace}}
